### PR TITLE
fix(nextjs): Handle dynamicIO errors when request apis are accessed on prerender

### LINKED ISSUE #4445: Next.js 15 canary with experimental PPR + dynamicIO issue calling headers()
### Preliminary Checks

- [X] I have reviewed the documentation: https://clerk.com/docs

- [X] I have searched for existing issues: https://github.com/clerk/javascript/issues

- [X] I have not already reached out to Clerk support via email or Discord (if you have, no need to open an issue here)

- [X] This issue is not a question, general help request, or anything other than a bug report directly related to Clerk. Please ask questions in our Discord community: https://clerk.com/discord.

### Reproduction

https://github.com/Jussinevavuori/clerk-next15-ppr-dynamicio-headers-issue

### Publishable key

pk_test_ZnJlc2gtcmFtLTkxLmNsZXJrLmFjY291bnRzLmRldiQ

### Description

**Steps to reproduce:**

1. Clone reproduction repo.
2. Install dependencies with `bun install`.
3. Copy `.env.example` as `.env` and set up the required Clerk `.env` variables.
4. Run with `bun dev`.

**Expected behavior:**

Should not cause any errors.

**Actual behavior:**

Causes below error.

```
 ⨯ unhandledRejection: Error: Clerk: auth() and currentUser() are only supported in App Router (/app directory).
If you're using /pages, try getAuth() instead.
Original error: Error: During prerendering, `headers()` rejects when the prerender is complete. Typically these errors are handled by React but if you move `headers()` to a different context by using `setTimeout`, `unstable_after`, or similar functions you may observe this error and you should handle it in that context.
    at buildRequestLike (turbopack://[project]/node_modules/@clerk/nextjs/src/app-router/server/utils.ts:35:10)
    at async getDynamicClerkState2 (turbopack://[project]/node_modules/@clerk/nextjs/src/app-router/server/ClerkProvider.tsx:17:18)
  33 |     }
  34 |
> 35 |     throw new Error(
     |          ^
  36 |       `Clerk: auth() and currentUser() are only supported in App Router (/app directory).\nIf you're using /pages, try getAuth() instead.\nOriginal error: ${e}`,
  37 |     );
  38 |   }

```

### Environment

```Shell
System:
    OS: macOS 15.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 201.53 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.20.2 - ~/.nvm/versions/node/v18.20.2/bin/node
    Yarn: 1.22.22 - ~/.nvm/versions/node/v18.20.2/bin/yarn
    npm: 10.5.0 - ~/.nvm/versions/node/v18.20.2/bin/npm
    pnpm: 9.0.1 - ~/.nvm/versions/node/v18.20.2/bin/pnpm
    bun: 1.1.32 - ~/.bun/bin/bun
    Watchman: 2024.10.28.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 130.0.6723.92
    Safari: 18.1
```

### PR DESCRIPTION
**Pull request by panteliselef**
## Description

This PR resolves the issue seen below when a next.js application is using `dynamicIO: true`.

```
 ⨯ unhandledRejection: Error: Clerk: auth() and currentUser() are only supported in App Router (/app directory).
If you're using /pages, try getAuth() instead.
Original error: Error: During prerendering, `headers()` rejects when the prerender is complete. Typically these errors are handled by React but if you move `headers()` to a different context by using `setTimeout`, `unstable_after`, or similar functions you may observe this error and you should handle it in that context.
    at buildRequestLike (turbopack://[project]/node_modules/@clerk/nextjs/src/app-router/server/utils.ts:35:10)
    at async getDynamicClerkState2 (turbopack://[project]/node_modules/@clerk/nextjs/src/app-router/server/ClerkProvider.tsx:17:18)
  33 |     }
  34 |
> 35 |     throw new Error(
     |          ^
  36 |       `Clerk: auth() and currentUser() are only supported in App Router (/app directory).\nIf you're using /pages, try getAuth() instead.\nOriginal error: ${e}`,
  37 |     );
  38 |   }
```

### What is happening

There seems to be an issue when awaiting `header()` inside another scope. When we do that we need to always await that function.

Example with minimal reproduction 

✅ Works
```tsx
export async function ClerkProvider() {
 await (async () => {
    await headers();
  })()

  return <>{props.children}</>;
}
```
❌ Throws
```tsx
export async function ClerkProvider() {
  (async () => {
    await headers();
  })()

  return <>{props.children}</>;
}
```

Example with our structure
✅ This code works properly and will not throw **unhandledRejection**
```tsx
const getDynamicState = React.cache(async () => {
  await headers();
  return {};
});

const getNonce = React.cache(async () => {
  await headers();
  return "nonce";
});

export async function ClerkProvider(
  props: PropsWithChildren<{ dynamic: boolean }>
) {
  await getNonce();
  await getDynamicState();

  return <>{props.children}</>;
}
```

❌ This code works throws **unhandledRejection**
```tsx
const getDynamicState = React.cache(async () => {
  // await buildRequest();
  await headers();
  return {};
});

const getNonce = React.cache(async () => {
  await headers();
  return "nonce";
});

export async function ClerkProvider(
  props: PropsWithChildren<{ dynamic: boolean }>
) {
  let statePromise: Promise<unknown> = Promise.resolve(null);
  let noncePromise = Promise.resolve("");

  if (props.dynamic) {
    noncePromise = getNonce();
    statePromise = getDynamicState();
  }

  await noncePromise;
  await statePromise;

  return <>{props.children}</>;
}
```

Fixes #4445

## Checklist

- [ ] `pnpm test` runs as expected.
- [ ] `pnpm build` runs as expected.
- [ ] (If applicable) [JSDoc comments](https://jsdoc.app/about-getting-started.html) have been added or updated for any package exports
- [ ] (If applicable) [Documentation](https://github.com/clerk/clerk-docs) has been updated

## Type of change

- [ ] 🐛 Bug fix
- [ ] 🌟 New feature
- [ ] 🔨 Breaking change
- [ ] 📖 Refactoring / dependency upgrade / documentation
- [ ] other:

### CODE REVIEW

**Comment by panteliselef** [comment]
!snapshot

**Comment by clerk-cookie** [comment]
Hey @panteliselef - the snapshot version command generated the following package versions:
| Package | Version |
| --- | --- |
| @clerk/nextjs | 6.9.7-snapshot.v20250101161910 |

Tip: Use the snippet copy button below to quickly install the required packages.
`@clerk/nextjs`
```sh
npm i @clerk/nextjs@6.9.7-snapshot.v20250101161910 --save-exact
```

File: packages/nextjs/src/app-router/server/ClerkProvider.tsx [hunk 1]
```diff
@@ -27,21 +26,35 @@ export async function ClerkProvider(
...
+        /**
+         * For some reason, Next 13 requires that functions which call `headers()` are awaited where they are invoked.
+         * Without the await here, Next will throw a DynamicServerError during build.
+         */
+        return Promise.resolve(await getDynamicClerkState());
+      } else {
+        return getDynamicClerkState();
+      }
+    }
+    return Promise.resolve(null);
```
Comment (jacekradko) [inline packages/nextjs/src/app-router/server/ClerkProvider.tsx:42]: [nit] Using guard clauses reduces indentation and makes it easier to read

```suggestion
    if (!dynamic) {
  		return Promise.resolve(null);
    }
	  if (isNext13) {
	    /**
	     * For some reason, Next 13 requires that functions which call `headers()` are awaited where they are invoked.
	     * Without the await here, Next will throw a DynamicServerError during build.
	     */
	    return Promise.resolve(await getDynamicClerkState());
	  } else {
	    return getDynamicClerkState();
	  }
```

File: packages/nextjs/src/app-router/server/ClerkProvider.tsx [hunk 2]
```diff
@@ -27,21 +26,35 @@ export async function ClerkProvider(
...
+        /**
+         * For some reason, Next 13 requires that functions which call `headers()` are awaited where they are invoked.
+         * Without the await here, Next will throw a DynamicServerError during build.
+         */
+        return Promise.resolve(await getNonceFromCSPHeader());
+      } else {
+        return getNonceFromCSPHeader();
+      }
     }
+    return Promise.resolve('');
```
Comment (jacekradko) [inline packages/nextjs/src/app-router/server/ClerkProvider.tsx:57]: [nit] convert to a guard clause

```suggestion
    if (dynamic) {
	    return Promise.resolve('');
    }
    if (isNext13) {
      /**
       * For some reason, Next 13 requires that functions which call `headers()` are awaited where they are invoked.
       * Without the await here, Next will throw a DynamicServerError during build.
       */
      return Promise.resolve(await getNonceFromCSPHeader());
    } else {
      return getNonceFromCSPHeader();
    }
```

**Review by jacekradko — APPROVED** [review]
👍🏼
