### PR TITLE
fix(remix): Get env variables in Cloudflare Pages context

### LINKED ISSUE #2778: secretKey not being detected in Remix + Cloudflare Pages
### Preliminary Checks

- [X] I have reviewed the documentation: [https://clerk.com/docs](https://clerk.com/docs)
- [X] I have searched for existing issues: [https://github.com/clerk/javascript/issues](https://github.com/clerk/javascript/issues)
- [X] I have not already reached out to Clerk support via email or Discord (if you have, no need to open an issue here)
- [X] This issue is not a question, general help request, or anything other than a bug report directly related to Clerk. Please ask questions in our Discord community: [https://clerk.com/discord](https://clerk.com/discord).

### Reproduction / Replay Link

[https://github.com/arjunyel/clerk-remix-vite-issue](https://github.com/arjunyel/clerk-remix-vite-issue)

### Publishable key

pk_test_c3BsZW5kaWQtcGVsaWNhbi05MS5jbGVyay5hY2NvdW50cy5kZXYk

### Description

**Steps to reproduce:**

1. Create the file `.dev.vars` and add

   ```env
   CLERK_PUBLISHABLE_KEY=
   CLERK_SECRET_KEY=
   ```
2. `npm run dev` and navigate to [http://localhost:5173/](http://localhost:5173/)

**Expected behavior:**

Loads page

**Actual behavior:**

```
Error: 🔒 Clerk: A secretKey or apiKey must be provided in order to use SSR and the exports from @clerk/remix/api.');
If your runtime supports environment variables, you can add a CLERK_SECRET_KEY or CLERK_API_KEY variable to your config.
Otherwise, you can pass a secretKey parameter to rootAuthLoader or getAuth.
```

### Environment

```Shell
System:
    OS: macOS 14.3.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 1.67 GB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.11.0 - ~/Library/Caches/fnm_multishells/11357_1707512011668/bin/node
    Yarn: 1.22.19 - ~/Library/Caches/fnm_multishells/11357_1707512011668/bin/yarn
    npm: 10.2.4 - ~/Library/Caches/fnm_multishells/11357_1707512011668/bin/npm
    pnpm: 8.10.2 - ~/Library/Caches/fnm_multishells/11357_1707512011668/bin/pnpm
    bun: 1.0.18 - /usr/local/bin/bun
  Browsers:
    Safari: 17.3.1
  npmPackages:
    @clerk/remix: ^3.1.18 => 3.1.18 
    @cloudflare/workers-types: ^4.20240208.0 => 4.20240208.0 
    @remix-run/cloudflare: ^2.6.0 => 2.6.0 
    @remix-run/cloudflare-pages: ^2.6.0 => 2.6.0 
    @remix-run/dev: ^2.6.0 => 2.6.0 
    @remix-run/react: ^2.6.0 => 2.6.0 
    @types/react: ^18.2.55 => 18.2.55 
    @types/react-dom: ^18.2.19 => 18.2.19 
    @typescript-eslint/eslint-plugin: ^6.21.0 => 6.21.0 
    eslint: ^8.56.0 => 8.56.0 
    eslint-import-resolver-typescript: ^3.6.1 => 3.6.1 
    eslint-plugin-import: ^2.29.1 => 2.29.1 
    eslint-plugin-jsx-a11y: ^6.8.0 => 6.8.0 
    eslint-plugin-react: ^7.33.2 => 7.33.2 
    eslint-plugin-react-hooks: ^4.6.0 => 4.6.0 
    isbot: ^4.4.0 => 4.4.0 
    miniflare: ^3.20240129.1 => 3.20240129.1 
    node-fetch: ^3.3.2 => 3.3.2 
    react: ^18.2.0 => 18.2.0 
    react-dom: ^18.2.0 => 18.2.0 
    typescript: ^5.3.3 => 5.3.3 
    vite: ^5.1.1 => 5.1.1 
    vite-tsconfig-paths: ^4.3.1 => 4.3.1 
    wrangler: ^3.28.1 => 3.28.1
```

### PR DESCRIPTION
**Pull request by arjunyel**
## Description

Fixes #2778

Remix + Cloudflare pages now accesses  environment variables via `context.cloudflare.env` https://remix.run/blog/remix-vite-stable#cloudflare-pages-support  

## Checklist

- [X] `npm test` runs as expected.
- [X] `npm run build` runs as expected.
- [ ] (If applicable) [JSDoc comments](https://jsdoc.app/about-getting-started.html) have been added or updated for any package exports
- [ ] (If applicable) [Documentation](https://github.com/clerk/clerk-docs) has been updated

## Type of change

- [X] 🐛 Bug fix
- [ ] 🌟 New feature
- [ ] 🔨 Breaking change
- [ ] 📖 Refactoring / dependency upgrade / documentation
- [ ] other:

### CODE REVIEW

File: packages/remix/src/utils/utils.ts [hunk 1]
```diff
@@ -32,14 +36,19 @@ export function assertValidClerkState(val: any): asserts val is ClerkState | und
  * @returns string
  */
 export const getEnvVariable = (name: string, context: AppLoadContext | undefined): string => {
+  // Remix + Cloudflare pages
+  if (typeof (context?.cloudflare as CloudflareEnv)?.env !== 'undefined') {
```
Comment (octoper) [inline packages/remix/src/utils/utils.ts:40]: Would be nice to have everything in one place so we can move those lines together with the rest of Cloudflare Pages check.

File: packages/remix/src/utils/utils.ts [hunk 2]
```diff
@@ -32,14 +36,19 @@ export function assertValidClerkState(val: any): asserts val is ClerkState | und
...
+
   // Node envs
   if (typeof process !== 'undefined') {
     return (process.env && process.env[name]) || '';
   }
 
   // Cloudflare pages
   if (typeof context !== 'undefined') {
-    const contextEnv = context?.env as Record<string, string>;
+    const contextEnv = (context as CloudflareEnv)?.env;
```
Comment (octoper) [inline packages/remix/src/utils/utils.ts:51]: We can change to the following line to:
```suggestion
    const baseContext = (context?.cloudflare || context) as Record<string, unknown>;
    const contextEnv = (baseContext?.env || baseContext?.env) as Record<string, string>;
```

File: packages/remix/src/utils/utils.ts [hunk 3]
```diff
@@ -24,6 +24,10 @@ export function assertValidClerkState(val: any): asserts val is ClerkState | und
   }
 }
 
+type CloudflareEnv = {
```
Comment (octoper) [inline packages/remix/src/utils/utils.ts:27]: This can be removed if the suggestion I have provided is applied

**Comment by arjunyel** [comment]
@octoper the reason I didn't combine the Remix + Cloudflare Pages and the Cloudflare Pages check is I was worried about it being a breaking change. `context.cloudflare.env` has to be checked before `process.env` because `process.env` is available in the Vite dev environment but does not have the variables from `.dev.vars` loaded into it. So I would need to move the Cloudflare Pages check in front of the `process.env` check which would be a breaking change. 

Hope that makes sense 😄

**Comment by JacobMGEvans** [comment]
Just bumping this, there are additional Remix users running into this problem. Thanks :)

File: packages/remix/src/utils/utils.ts (hunk 1 above)
Comment (nikosdouvlis) [reply packages/remix/src/utils/utils.ts:40]: We probably don't need the `typeof` check here as this is testing a local identifier and not the global (`window`/`globalThis`) namespace but everything else makes sense to me :)

**Review by nikosdouvlis — APPROVED** [review]
Thank you for your contribution @arjunyel , this makes total sense to me!
Merging so we can get this out as soon as possible.
